FROM rust:slim-bullseye AS builder

WORKDIR /app

COPY ./Cargo.* ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo fetch

COPY ./src ./src

RUN cargo build --release --locked



FROM scratch
COPY --from=builder /app/target/release/api-rust /app
CMD ["app"]
